"""
app.py — Amazon Sales | High-Value Order Classifier
====================================================
Streamlit dashboard that evaluates 5 trained classification models on an
uploaded test dataset (test_data.csv produced by train_models.py).

Sidebar : dataset uploader + model dropdown
Main    : dataset overview, 6 evaluation metrics, confusion matrix,
          classification report
"""

import joblib
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import streamlit as st
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    precision_score,
    recall_score,
    roc_auc_score,
)

# ---------------------------------------------------------------- page setup
st.set_page_config(
    page_title="Amazon High-Value Order Classifier",
    page_icon="📦",
    layout="wide",
)

AMAZON_MODEL_FILES = {
    "Logistic Regression": "model/Logistic_Regression.joblib",
    "Decision Tree": "model/Decision_Tree.joblib",
    "KNN": "model/KNN.joblib",
    "Naive Bayes": "model/Naive_Bayes.joblib",
    "Random Forest": "model/Random_Forest.joblib",
}


@st.cache_resource
def load_amazon_artifacts():
    """Load the scaler and column metadata saved during training."""
    amazon_scaler = joblib.load("model/scaler.joblib")
    amazon_meta = joblib.load("model/columns.joblib")
    return amazon_scaler, amazon_meta


@st.cache_resource
def load_amazon_model(name: str):
    return joblib.load(AMAZON_MODEL_FILES[name])


amazon_scaler, amazon_meta = load_amazon_artifacts()
AMAZON_TARGET_COLUMN = amazon_meta["target_column"]

# ------------------------------------------------------------------- sidebar
st.sidebar.title("⚙️ Controls")
uploaded_amazon_csv = st.sidebar.file_uploader(
    "Upload test_data.csv", type=["csv"],
    help="Use the test_data.csv generated by train_models.py",
)
selected_amazon_model = st.sidebar.selectbox(
    "Choose Model", list(AMAZON_MODEL_FILES.keys())
)
st.sidebar.markdown("---")
st.sidebar.caption(
    f"**Target:** `{AMAZON_TARGET_COLUMN}`\n\n"
    f"1 = order total above the training median "
    f"(₹/$ {amazon_meta['threshold']:.2f}), 0 = at/below it."
)

# -------------------------------------------------------------------- header
st.title("📦 Amazon Sales — High-Value Order Classifier")
st.markdown(
    "Predicting whether an order is a **high-value purchase** from its "
    "attributes (quantity, unit price, discount, tax, shipping, category, "
    "brand, payment method, country and order-date features). "
    "Five classifiers were trained on 80,000 orders; upload the held-out "
    "test split to evaluate them."
)

if uploaded_amazon_csv is None:
    st.info("⬅️ Upload **test_data.csv** from the sidebar to begin.")
    st.stop()

# ------------------------------------------------------------- load the data
try:
    amazon_orders_df = pd.read_csv(uploaded_amazon_csv)
except Exception as exc:
    st.error(f"Could not read the CSV file: {exc}")
    st.stop()

if AMAZON_TARGET_COLUMN not in amazon_orders_df.columns:
    st.error(
        f"The uploaded file has no `{AMAZON_TARGET_COLUMN}` column, so metrics cannot be "
        "computed. Please upload the test_data.csv produced by "
        "train_models.py."
    )
    st.stop()

amazon_y_true = amazon_orders_df[AMAZON_TARGET_COLUMN]
amazon_X = amazon_orders_df.drop(columns=[AMAZON_TARGET_COLUMN])

# Align columns with the training feature order, then scale numerics with
# the scaler fitted on the training split only (no leakage).
amazon_X = amazon_X.reindex(columns=amazon_meta["feature_columns"], fill_value=0)
amazon_X[amazon_meta["numeric_columns"]] = amazon_scaler.transform(
    amazon_X[amazon_meta["numeric_columns"]]
)

with st.expander("🔍 Preview uploaded dataset"):
    c1, c2, c3 = st.columns(3)
    c1.metric("Rows", f"{len(amazon_orders_df):,}")
    c2.metric("Features", amazon_X.shape[1])
    c3.metric(
        "High-value share", f"{amazon_y_true.mean() * 100:.1f}%"
    )
    st.dataframe(amazon_orders_df.head(10), use_container_width=True)

# ---------------------------------------------------------------- prediction
amazon_model = load_amazon_model(selected_amazon_model)
amazon_y_pred = amazon_model.predict(amazon_X)
amazon_y_prob = amazon_model.predict_proba(amazon_X)[:, 1]  # AUC needs probabilities

# ------------------------------------------------------------------- metrics
st.subheader(f"📊 Evaluation Metrics — {selected_amazon_model}")

amazon_accuracy = accuracy_score(amazon_y_true, amazon_y_pred)
amazon_auc = roc_auc_score(amazon_y_true, amazon_y_prob)
amazon_precision = precision_score(amazon_y_true, amazon_y_pred)
amazon_recall = recall_score(amazon_y_true, amazon_y_pred)
amazon_f1 = f1_score(amazon_y_true, amazon_y_pred)
amazon_mcc = matthews_corrcoef(amazon_y_true, amazon_y_pred)

row1 = st.columns(3)
row1[0].metric(label="Accuracy", value=round(amazon_accuracy, 4))
row1[1].metric(label="AUC Score", value=round(amazon_auc, 4))
row1[2].metric(label="Precision", value=round(amazon_precision, 4))

row2 = st.columns(3)
row2[0].metric(label="Recall", value=round(amazon_recall, 4))
row2[1].metric(label="F1 Score", value=round(amazon_f1, 4))
row2[2].metric(label="MCC", value=round(amazon_mcc, 4))

# --------------------------------------------------------- confusion matrix
left, right = st.columns([1, 1])

with left:
    st.subheader("🧮 Confusion Matrix")
    amazon_confusion_matrix = confusion_matrix(amazon_y_true, amazon_y_pred)
    fig, ax = plt.subplots(figsize=(5, 4))
    sns.heatmap(
        amazon_confusion_matrix, annot=True, fmt="d", cmap="Blues", cbar=False,
        xticklabels=["Regular (0)", "High-Value (1)"],
        yticklabels=["Regular (0)", "High-Value (1)"],
        ax=ax,
    )
    ax.set_xlabel("Predicted label")
    ax.set_ylabel("True label")
    ax.set_title(selected_amazon_model)
    st.pyplot(fig)

with right:
    st.subheader("📋 Classification Report")
    amazon_classification_report = classification_report(
        amazon_y_true, amazon_y_pred,
        target_names=["Regular (0)", "High-Value (1)"],
        output_dict=True,
    )
    st.dataframe(
        pd.DataFrame(amazon_classification_report).transpose().round(4),
        use_container_width=True,
    )
    st.caption(
        "Tip: switch models in the sidebar to compare how each algorithm "
        "handles the same test split."
    )
