"""
app.py — Amazon Sales | High-Value Order Classifier
====================================================
Streamlit dashboard that evaluates 5 trained classification models on an
uploaded test dataset (test_data.csv produced by train_models.py).

Sidebar : dataset uploader + model dropdown
Main    : dataset overview, 6 evaluation metrics, confusion matrix,
          classification report
"""

import joblib
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import streamlit as st
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    precision_score,
    recall_score,
    roc_auc_score,
)

# ---------------------------------------------------------------- page setup
st.set_page_config(
    page_title="Amazon High-Value Order Classifier",
    page_icon="📦",
    layout="wide",
)

MODEL_FILES = {
    "Logistic Regression": "model/Logistic_Regression.joblib",
    "Decision Tree": "model/Decision_Tree.joblib",
    "KNN": "model/KNN.joblib",
    "Naive Bayes": "model/Naive_Bayes.joblib",
    "Random Forest": "model/Random_Forest.joblib",
}


@st.cache_resource
def load_artifacts():
    """Load the scaler and column metadata saved during training."""
    scaler = joblib.load("model/scaler.joblib")
    meta = joblib.load("model/columns.joblib")
    return scaler, meta


@st.cache_resource
def load_model(name: str):
    return joblib.load(MODEL_FILES[name])


scaler, meta = load_artifacts()
TARGET = meta["target_column"]

# ------------------------------------------------------------------- sidebar
st.sidebar.title("⚙️ Controls")
uploaded_file = st.sidebar.file_uploader(
    "Upload test_data.csv", type=["csv"],
    help="Use the test_data.csv generated by train_models.py",
)
selected_model = st.sidebar.selectbox(
    "Choose Model", list(MODEL_FILES.keys())
)
st.sidebar.markdown("---")
st.sidebar.caption(
    f"**Target:** `{TARGET}`\n\n"
    f"1 = order total above the training median "
    f"(₹/$ {meta['threshold']:.2f}), 0 = at/below it."
)

# -------------------------------------------------------------------- header
st.title("📦 Amazon Sales — High-Value Order Classifier")
st.markdown(
    "Predicting whether an order is a **high-value purchase** from its "
    "attributes (quantity, unit price, discount, tax, shipping, category, "
    "brand, payment method, country and order-date features). "
    "Five classifiers were trained on 80,000 orders; upload the held-out "
    "test split to evaluate them."
)

if uploaded_file is None:
    st.info("⬅️ Upload **test_data.csv** from the sidebar to begin.")
    st.stop()

# ------------------------------------------------------------- load the data
try:
    data = pd.read_csv(uploaded_file)
except Exception as exc:
    st.error(f"Could not read the CSV file: {exc}")
    st.stop()

if TARGET not in data.columns:
    st.error(
        f"The uploaded file has no `{TARGET}` column, so metrics cannot be "
        "computed. Please upload the test_data.csv produced by "
        "train_models.py."
    )
    st.stop()

y_true = data[TARGET]
X = data.drop(columns=[TARGET])

# Align columns with the training feature order, then scale numerics with
# the scaler fitted on the training split only (no leakage).
X = X.reindex(columns=meta["feature_columns"], fill_value=0)
X[meta["numeric_columns"]] = scaler.transform(X[meta["numeric_columns"]])

with st.expander("🔍 Preview uploaded dataset"):
    c1, c2, c3 = st.columns(3)
    c1.metric("Rows", f"{len(data):,}")
    c2.metric("Features", X.shape[1])
    c3.metric(
        "High-value share", f"{y_true.mean() * 100:.1f}%"
    )
    st.dataframe(data.head(10), use_container_width=True)

# ---------------------------------------------------------------- prediction
model = load_model(selected_model)
y_pred = model.predict(X)
y_prob = model.predict_proba(X)[:, 1]  # AUC needs probabilities

# ------------------------------------------------------------------- metrics
st.subheader(f"📊 Evaluation Metrics — {selected_model}")

acc = accuracy_score(y_true, y_pred)
auc = roc_auc_score(y_true, y_prob)
prec = precision_score(y_true, y_pred)
rec = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)
mcc = matthews_corrcoef(y_true, y_pred)

row1 = st.columns(3)
row1[0].metric(label="Accuracy", value=round(acc, 4))
row1[1].metric(label="AUC Score", value=round(auc, 4))
row1[2].metric(label="Precision", value=round(prec, 4))

row2 = st.columns(3)
row2[0].metric(label="Recall", value=round(rec, 4))
row2[1].metric(label="F1 Score", value=round(f1, 4))
row2[2].metric(label="MCC", value=round(mcc, 4))

# --------------------------------------------------------- confusion matrix
left, right = st.columns([1, 1])

with left:
    st.subheader("🧮 Confusion Matrix")
    cm = confusion_matrix(y_true, y_pred)
    fig, ax = plt.subplots(figsize=(5, 4))
    sns.heatmap(
        cm, annot=True, fmt="d", cmap="Blues", cbar=False,
        xticklabels=["Regular (0)", "High-Value (1)"],
        yticklabels=["Regular (0)", "High-Value (1)"],
        ax=ax,
    )
    ax.set_xlabel("Predicted label")
    ax.set_ylabel("True label")
    ax.set_title(selected_model)
    st.pyplot(fig)

with right:
    st.subheader("📋 Classification Report")
    report = classification_report(
        y_true, y_pred,
        target_names=["Regular (0)", "High-Value (1)"],
        output_dict=True,
    )
    st.dataframe(
        pd.DataFrame(report).transpose().round(4),
        use_container_width=True,
    )
    st.caption(
        "Tip: switch models in the sidebar to compare how each algorithm "
        "handles the same test split."
    )
